buzzwords_keywords = [
    # Partnership/Collaborations
    'official',
    'partner',
    'big announcement',
    'announce',
    'great news',
    'government',
    'national',
    'alliance',
    'partnership',
    'collab',
    'upgrade',
    'release',
	'announcing'
	'announced',

	# Exchange Keywords
    'list',
    'distribute',
    'add',
    'token',
    'trading',
    'open',
    'listed',
    'available',
    'new',
    'support',
	'Launch of',
	'launch',
	'launced',
	'launching',
	'addition',
	'added',
	'adding',
]